services:
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Src/Services/Catalog/Catalog.Api/Dockerfile
      
  catalogdb:
    image: postgres
    
  pgadmin:
    image: dpage/pgadmin4:latest

volumes:
  postgres_catalog: