# This is a generated file. Not intended for manual editing.
services:
  catalog.api:
    build:
      context: "C:\\Projects\\WebDev\\EShopMicroservices"
      dockerfile: "Src/Services/Catalog/Catalog.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Catalog.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalog.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\User\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Projects\\WebDev\\EShopMicroservices\\Src\\Services\\Catalog\\Catalog.Api:/app:rw"
    - "C:\\Projects\\WebDev\\EShopMicroservices:/src:rw"
    working_dir: "/app"
